apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mydeployment
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mydeployment
    spec:
      containers:
        - name: helloworld
          image: helloworld-webserver:1.0
          env:
          - name: MYBASEVAR
            valueFrom:
              configMapKeyRef:
                name: example-configmap-base
                key: base.properties
          - name: MYOVERLAYVAR
            valueFrom:
              configMapKeyRef:
                name: example-configmap-overlay
                key: overlay.properties